apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-app1
spec:
  host: istio-app1
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2